import type { DashboardModuleDefinition } from "../shared/dashboard/module-contracts";

export const dashboardModules: DashboardModuleDefinition[] = [
  {
    id: "inbox",
    path: "inbox/:conversationId?",
    navTo: "/dashboard/inbox",
    navLabel: "Inbox",
    subtitle: "Live conversations",
    icon: "chats",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/inbox/route"),
    legacyAliases: ["conversations"],
    featureFlag: "dashboard.inbox",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "leads",
    path: "leads",
    navTo: "/dashboard/leads",
    navLabel: "Contacts",
    subtitle: "Customer directory",
    icon: "leads",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/contacts/route"),
    featureFlag: "dashboard.contacts",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "templates",
    path: "templates/*",
    navTo: "/dashboard/settings/templates",
    navLabel: "Templates",
    subtitle: "Redirect to WhatsApp templates",
    icon: "templates",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/templates/route"),
    featureFlag: "dashboard.templates",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "broadcast",
    path: "broadcast/*",
    navTo: "/dashboard/broadcast",
    navLabel: "Broadcast",
    subtitle: "Campaigns and retargeting",
    icon: "broadcast",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/broadcast/route"),
    featureFlag: "dashboard.templates",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "sequence",
    path: "sequence/*",
    navTo: "/dashboard/sequence",
    navLabel: "Sequence",
    subtitle: "Behavior-based follow ups",
    icon: "sequence",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/sequence/route"),
    featureFlag: "dashboard.sequence",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "analytics",
    path: "analytics/*",
    navTo: "/dashboard/analytics",
    navLabel: "Analytics",
    subtitle: "Delivery and reports",
    icon: "analytics",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/analytics/route"),
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "billing",
    path: "billing",
    navTo: "/dashboard/billing",
    navLabel: "Billing",
    subtitle: "Credits and invoices",
    icon: "billing",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/billing/route"),
    legacyAliases: ["billing"],
    featureFlag: "dashboard.billing",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "agents",
    path: "agents",
    navTo: "/dashboard/agents",
    navLabel: "Agents",
    subtitle: "Shared workflow",
    icon: "agents",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/agents/route"),
    legacyAliases: ["bot_agents"],
    featureFlag: "dashboard.agents",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-flows",
    path: "studio/flows/*",
    navTo: "/dashboard/studio/flows",
    navLabel: "Flows",
    subtitle: "Visual bot builder",
    icon: "flows",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/flows/route"),
    legacyAliases: ["bot_flows", "flow_builder"],
    featureFlag: "dashboard.studio.flows",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-knowledge",
    path: "studio/knowledge",
    navTo: "/dashboard/studio/knowledge",
    navLabel: "Knowledge",
    subtitle: "Manage sources",
    icon: "knowledge",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/knowledge/route"),
    legacyAliases: ["knowledge"],
    featureFlag: "dashboard.studio.knowledge",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-personality",
    path: "studio/personality",
    navTo: "/dashboard/studio/personality",
    navLabel: "Personality",
    subtitle: "Behavior and tone",
    icon: "personality",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/personality/route"),
    legacyAliases: ["chatbot_personality"],
    featureFlag: "dashboard.studio.personality",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-review",
    path: "studio/review",
    navTo: "/dashboard/studio/review",
    navLabel: "AI Review",
    subtitle: "Resolve low confidence",
    icon: "unanswered",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/review/route"),
    legacyAliases: ["unanswered_questions"],
    featureFlag: "dashboard.studio.review",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-test",
    path: "studio/test",
    navTo: "/dashboard/studio/test",
    navLabel: "Test Chat",
    subtitle: "Live widget test",
    icon: "test",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/test/route"),
    legacyAliases: ["test_chatbot"],
    featureFlag: "dashboard.studio.test",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-web",
    path: "settings/web",
    navTo: "/dashboard/settings/web",
    navLabel: "Website",
    subtitle: "Widget setup",
    icon: "settings",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/web/route"),
    featureFlag: "dashboard.settings.web",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-qr",
    path: "settings/qr",
    navTo: "/dashboard/settings/qr",
    navLabel: "QR Channel",
    subtitle: "WhatsApp QR",
    icon: "chats",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/qr/route"),
    featureFlag: "dashboard.settings.qr",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-api",
    path: "settings/api",
    navTo: "/dashboard/settings/api",
    navLabel: "API Channel",
    subtitle: "Official WhatsApp API",
    icon: "settings",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/api/route"),
    featureFlag: "dashboard.settings.api",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-templates",
    path: "settings/templates/*",
    navTo: "/dashboard/settings/templates",
    navLabel: "Templates",
    subtitle: "WhatsApp message templates",
    icon: "templates",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/templates/route"),
    featureFlag: "dashboard.templates",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-contact-fields",
    path: "settings/contact-fields",
    navTo: "/dashboard/settings/contact-fields",
    navLabel: "Contact Fields",
    subtitle: "Custom contact fields",
    icon: "leads",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/contact-fields/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  {
    id: "settings-webhooks",
    path: "settings/webhooks",
    navTo: "/dashboard/settings/webhooks",
    navLabel: "Generic Webhooks",
    subtitle: "Webhook automations",
    icon: "settings",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/webhooks/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  // ── Account section ────────────────────────────────────────────────────────
  {
    id: "account-details",
    path: "account/details",
    navTo: "/dashboard/account/details",
    navLabel: "Account Details",
    subtitle: "Workspace name, timezone, and preferences",
    icon: "account",
    section: "account",
    lazyRoute: () => import("../modules/dashboard/account/details/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  {
    id: "account-subscription",
    path: "account/subscription",
    navTo: "/dashboard/account/subscription",
    navLabel: "Subscription",
    subtitle: "Plan, billing, and renewals",
    icon: "billing",
    section: "account",
    lazyRoute: () => import("../modules/dashboard/account/subscription/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  {
    id: "account-credits",
    path: "account/credits",
    navTo: "/dashboard/account/credits",
    navLabel: "Message Credits",
    subtitle: "WhatsApp message credit balance and history",
    icon: "templates",
    section: "account",
    lazyRoute: () => import("../modules/dashboard/account/credits/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  {
    id: "account-ai-wallet",
    path: "account/ai-wallet",
    navTo: "/dashboard/account/ai-wallet",
    navLabel: "AI Wallet",
    subtitle: "AI token usage and top-up packs",
    icon: "agents",
    section: "account",
    lazyRoute: () => import("../modules/dashboard/account/ai-wallet/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  {
    id: "account-profile",
    path: "account/profile",
    navTo: "/dashboard/account/profile",
    navLabel: "Profile & Password",
    subtitle: "Your name, email, and password",
    icon: "personality",
    section: "account",
    lazyRoute: () => import("../modules/dashboard/account/profile/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  },
  {
    id: "account-users",
    path: "account/users",
    navTo: "/dashboard/account/users",
    navLabel: "Users & Teams",
    subtitle: "Invite members and manage roles",
    icon: "leads",
    section: "account",
    lazyRoute: () => import("../modules/dashboard/account/users/route"),
    prefetchStrategy: "code",
    requiresAuth: true
  }
];
