import type { DashboardModuleDefinition } from "../shared/dashboard/module-contracts";

export const dashboardModules: DashboardModuleDefinition[] = [
  {
    id: "inbox",
    path: "inbox/:conversationId?",
    navTo: "/dashboard/inbox",
    navLabel: "Inbox",
    subtitle: "Live conversations",
    icon: "chats",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/inbox/route"),
    legacyAliases: ["conversations"],
    featureFlag: "dashboard.inbox",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "leads",
    path: "leads",
    navTo: "/dashboard/leads",
    navLabel: "Leads",
    subtitle: "Priority queue",
    icon: "leads",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/leads/route"),
    legacyAliases: ["leads"],
    featureFlag: "dashboard.leads",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "templates",
    path: "templates",
    navTo: "/dashboard/templates",
    navLabel: "Templates",
    subtitle: "Broadcast templates",
    icon: "templates",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/templates/route"),
    featureFlag: "dashboard.templates",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "billing",
    path: "billing",
    navTo: "/dashboard/billing",
    navLabel: "Billing",
    subtitle: "Credits and invoices",
    icon: "billing",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/billing/route"),
    legacyAliases: ["billing"],
    featureFlag: "dashboard.billing",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "agents",
    path: "agents",
    navTo: "/dashboard/agents",
    navLabel: "Agents",
    subtitle: "Shared workflow",
    icon: "agents",
    section: "main",
    lazyRoute: () => import("../modules/dashboard/agents/route"),
    legacyAliases: ["bot_agents"],
    featureFlag: "dashboard.agents",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-knowledge",
    path: "studio/knowledge",
    navTo: "/dashboard/studio/knowledge",
    navLabel: "Knowledge",
    subtitle: "Manage sources",
    icon: "knowledge",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/knowledge/route"),
    legacyAliases: ["knowledge"],
    featureFlag: "dashboard.studio.knowledge",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-personality",
    path: "studio/personality",
    navTo: "/dashboard/studio/personality",
    navLabel: "Personality",
    subtitle: "Behavior and tone",
    icon: "personality",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/personality/route"),
    legacyAliases: ["chatbot_personality"],
    featureFlag: "dashboard.studio.personality",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-review",
    path: "studio/review",
    navTo: "/dashboard/studio/review",
    navLabel: "AI Review",
    subtitle: "Resolve low confidence",
    icon: "unanswered",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/review/route"),
    legacyAliases: ["unanswered_questions"],
    featureFlag: "dashboard.studio.review",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "studio-test",
    path: "studio/test",
    navTo: "/dashboard/studio/test",
    navLabel: "Test Chat",
    subtitle: "Live widget test",
    icon: "test",
    section: "studio",
    lazyRoute: () => import("../modules/dashboard/studio/test/route"),
    legacyAliases: ["test_chatbot"],
    featureFlag: "dashboard.studio.test",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-web",
    path: "settings/web",
    navTo: "/dashboard/settings/web",
    navLabel: "Website",
    subtitle: "Widget setup",
    icon: "settings",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/web/route"),
    featureFlag: "dashboard.settings.web",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-qr",
    path: "settings/qr",
    navTo: "/dashboard/settings/qr",
    navLabel: "QR Channel",
    subtitle: "WhatsApp QR",
    icon: "chats",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/qr/route"),
    featureFlag: "dashboard.settings.qr",
    prefetchStrategy: "code+data",
    requiresAuth: true
  },
  {
    id: "settings-api",
    path: "settings/api",
    navTo: "/dashboard/settings/api",
    navLabel: "API Channel",
    subtitle: "Official WhatsApp API",
    icon: "settings",
    section: "settings",
    lazyRoute: () => import("../modules/dashboard/settings/api/route"),
    featureFlag: "dashboard.settings.api",
    prefetchStrategy: "code+data",
    requiresAuth: true
  }
];
